#!/bin/sh
# Build a WASM module for SQLCipher (leancrypto crypto provider) via
# Emscripten. This is an additive, standalone build path -- it does not
# touch or replace the native Linux build in main.mk, and it does not
# integrate with ext/wasm/ (upstream SQLite's own, much larger multi-variant
# WASM/JS-glue build for *vanilla* SQLite, which has no codec awareness).
#
# See wasm/README.md for prerequisites, usage, and current limitations.
#
# Usage:
#   tool/build-wasm.sh
#
# Environment overrides (all optional; auto-detected otherwise):
#   EMCC, EMAR, EMRANLIB   - paths to the Emscripten toolchain binaries.
#                            Resolution order: these env vars, then
#                            $PATH, then the system emscripten package
#                            path (/usr/lib/emscripten, as used by the
#                            Arch/CachyOS "emscripten" package).

set -e

TOP="$(cd "$(dirname "$0")/.." && pwd)"
LC_DIR="$TOP/third_party/leancrypto"
LC_BUILD_DIR="$LC_DIR/build-wasm"
GEN_DIR="$TOP/wasm/.gen"
OUT_DIR="$TOP/wasm"

# ---------------------------------------------------------------------------
# 1. Resolve the Emscripten toolchain
# ---------------------------------------------------------------------------
resolve_tool() {
	varname="$1"
	toolname="$2"
	eval "val=\${$varname:-}"
	if [ -n "$val" ]; then
		echo "$val"
		return 0
	fi
	if command -v "$toolname" >/dev/null 2>&1; then
		command -v "$toolname"
		return 0
	fi
	if [ -x "/usr/lib/emscripten/$toolname" ]; then
		echo "/usr/lib/emscripten/$toolname"
		return 0
	fi
	echo ""
	return 1
}

REAL_EMCC="$(resolve_tool EMCC emcc)" || {
	echo "error: emcc not found (checked \$EMCC, \$PATH, /usr/lib/emscripten). Install Emscripten or set \$EMCC." >&2
	exit 1
}
REAL_EMAR="$(resolve_tool EMAR emar)" || {
	echo "error: emar not found (checked \$EMAR, \$PATH, /usr/lib/emscripten)." >&2
	exit 1
}
REAL_EMRANLIB="$(resolve_tool EMRANLIB emranlib)" || {
	echo "error: emranlib not found (checked \$EMRANLIB, \$PATH, /usr/lib/emscripten)." >&2
	exit 1
}

echo "==> Using emcc:     $REAL_EMCC"
echo "==> Using emar:     $REAL_EMAR"
echo "==> Using emranlib: $REAL_EMRANLIB"
"$REAL_EMCC" --version | head -1

mkdir -p "$GEN_DIR" "$OUT_DIR"

# ---------------------------------------------------------------------------
# 2. Generate an emcc wrapper that filters flags Meson's compiler-argument
#    probing (cc.has_argument()) incorrectly reports as supported for the
#    wasm32-unknown-emscripten target -- confirmed empirically: leancrypto's
#    unmodified meson.build unconditionally adds -flto=auto/-ffat-lto-objects
#    whenever cc.has_argument() returns true for them (true here, but they
#    fail at actual compile time: "unsupported option ... for target
#    wasm32-unknown-emscripten"). Filtering here avoids ever having to patch
#    the vendored, pinned leancrypto submodule.
# ---------------------------------------------------------------------------
EMCC_WRAPPER="$GEN_DIR/emcc-wrapper.sh"
cat > "$EMCC_WRAPPER" <<EOF
#!/bin/bash
# Generated by tool/build-wasm.sh -- do not edit, re-run the script instead.
# Uses bash arrays (rather than naive string concatenation) so that
# multi-word arguments (e.g. -s EXPORTED_FUNCTIONS=[...]) survive filtering
# with their exact word boundaries intact.
args=()
for a in "\$@"; do
	case "\$a" in
		-flto=*|-ffat-lto-objects|-fcf-protection=*|-mbranch-protection=*)
			continue
			;;
	esac
	args+=("\$a")
done

# -msimd128 targets WASM's 128-bit SIMD instruction set. leancrypto's own
# hand-written asm (AVX2/AVX512/NEON) can't target wasm32 at all -- it's
# x86_64/ARM GNU-assembler syntax -- so this build always compiles
# leancrypto's *portable C* Keccak-p[1600] permutation (disable-asm=true
# below is a correctness requirement, not a missed optimization -- see
# doc/crypto.md's "Performance" section). -msimd128 lets LLVM's
# auto-vectorizer target that portable C with WASM SIMD instead of falling
# back to scalar wasm32 code; every WASM/Node runtime that can load this
# module already supports WASM SIMD (finalized in all major engines since
# 2021), so there is no compatibility downside to enabling it unconditionally.
exec "$REAL_EMCC" -msimd128 "\${args[@]}"
EOF
chmod +x "$EMCC_WRAPPER"

# ---------------------------------------------------------------------------
# 3. Generate the Meson cross-file from the template
# ---------------------------------------------------------------------------
CROSS_FILE="$TOP/third_party/wasm-cross.ini"
sed \
	-e "s|@EMCC@|$EMCC_WRAPPER|" \
	-e "s|@EMAR@|$REAL_EMAR|" \
	-e "s|@EMRANLIB@|$REAL_EMRANLIB|" \
	"$TOP/third_party/wasm-cross.ini.in" > "$CROSS_FILE"

# ---------------------------------------------------------------------------
# 4. Build leancrypto for wasm32
#
# Unlike the native build's LEANCRYPTO_MESON_OPTS in main.mk (which
# narrows leancrypto down to only what SQLCipher's own codec uses --
# Ascon-Keccak AEAD, SHA3, HKDF, HMAC), this WASM build deliberately keeps
# leancrypto's *default* (mostly "enabled") option set -- matching the
# reference secbits/leancrypto build's own leancrypto.js, which only
# overrides -Ddisable-asm=true -Defi=disabled -Dtests=disabled and leaves
# everything else (all PQC algorithms, all AES modes, all KDFs/DRNGs) at
# its default -- so that -Wl,--whole-archive/-s EXPORT_ALL=1 below can
# expose leancrypto's *whole* public API from this module, not just the
# narrow slice SQLCipher itself needs. (A first attempt reusing the
# native build's narrow option set failed to link here with
# "undefined symbol: lc_rng_zero / lc_aes" -- both real symbols that only
# get compiled in when at least one DRNG option or one aes_* option is
# enabled; leaving everything at its default avoids that entirely, and
# gives the requested full API surface as a side effect.)
#
# Kept disabled regardless of upstream defaults:
#   - disable-asm: portable C only -- required for the wasm32 target.
#   - efi: not meaningful under Emscripten (already disabled by default).
#   - apps, tests: leancrypto's own CLI tools/test binaries, not needed.
#   - x509_parser/x509_csr_parser/x509_generator/x509_csr_generator,
#     pkcs7_parser/pkcs7_generator, pkcs8_parser/pkcs8_generator: these
#     are GPLv2-licensed (see doc/crypto.md) and must stay disabled to
#     keep the vendored tree fully permissive/BSD-compatible, same
#     rationale as the native build.
# ---------------------------------------------------------------------------
LEANCRYPTO_MESON_OPTS="\
  --default-library=static \
  -Ddisable-asm=true \
  -Defi=disabled \
  -Dapps=disabled -Dtests=disabled \
  -Dx509_parser=disabled -Dx509_csr_parser=disabled \
  -Dx509_generator=disabled -Dx509_csr_generator=disabled \
  -Dpkcs7_parser=disabled -Dpkcs7_generator=disabled \
  -Dpkcs8_parser=disabled -Dpkcs8_generator=disabled"

echo "==> Configuring leancrypto for wasm32"
if [ ! -f "$LC_BUILD_DIR/build.ninja" ]; then
	# shellcheck disable=SC2086
	meson setup "$LC_BUILD_DIR" "$LC_DIR" --cross-file "$CROSS_FILE" $LEANCRYPTO_MESON_OPTS
fi
echo "==> Compiling leancrypto for wasm32"
meson compile -C "$LC_BUILD_DIR"

LC_LIB="$LC_BUILD_DIR/libleancrypto.a"
if [ ! -f "$LC_LIB" ]; then
	echo "error: $LC_LIB was not produced" >&2
	exit 1
fi

# ---------------------------------------------------------------------------
# 5. Generate the SQLCipher amalgamation (sqlite3.c/sqlite3.h), reusing the
#    existing autosetup/main.mk machinery rather than reimplementing it.
#    This only generates the amalgamation *text*; the actual compile with
#    the codec enabled happens in step 6 below via emcc directly.
# ---------------------------------------------------------------------------
echo "==> Generating sqlite3.c amalgamation"
mkdir -p "$GEN_DIR/build"
(
	cd "$GEN_DIR/build"
	if [ ! -f Makefile ]; then
		"$TOP/configure" --with-tempstore=yes --enable-fts5 \
			CFLAGS="-DSQLITE_HAS_CODEC -DSQLITE_EXTRA_INIT=sqlcipher_extra_init -DSQLITE_EXTRA_SHUTDOWN=sqlcipher_extra_shutdown"
	fi
	make sqlite3.c
)
cp "$GEN_DIR/build/sqlite3.c" "$GEN_DIR/sqlite3.c"
cp "$GEN_DIR/build/sqlite3.h" "$GEN_DIR/sqlite3.h"

# ---------------------------------------------------------------------------
# 6. Compile + link the WASM module: the amalgamation + the leancrypto
#    provider glue + the WASM RNG shim + the leancrypto raw-API wrapper,
#    statically linked against leancrypto's wasm32 libleancrypto.a.
#    Mirrors LEANCRYPTO_CFLAGS in main.mk, adjusted for the build-wasm
#    generated-header directories.
#
#    Exports EVERY public C symbol (both SQLite/SQLCipher's sqlite3_* API
#    and leancrypto's own lc_*/lc_wasm_* API) in this single module, the
#    same way the reference secbits/leancrypto build's leancrypto.js does
#    (-s EXPORT_ALL=1, -Wl,--export-all, -Wl,--no-gc-sections). Since the
#    amalgamation is compiled in amalgamation mode (SQLITE_PRIVATE=static),
#    this only picks up genuinely public functions, not SQLite's internal
#    helpers. -Wl,--whole-archive forces every object in libleancrypto.a
#    into the link (not just what crypto_leancrypto.c/leancrypto_wasm_api.c
#    happen to reference), so every compiled-in leancrypto function is
#    actually present to export -- this is also why
#    src/crypto_leancrypto_rng_wasm.c is included here defensively, in case
#    whole-archive pulls in any object with an unresolved reference to it.
# ---------------------------------------------------------------------------
echo "==> Linking wasm/sqlcipher.js + .wasm"

"$EMCC_WRAPPER" \
	-O2 --emit-symbol-map \
	-DSQLITE_HAS_CODEC \
	-DSQLITE_EXTRA_INIT=sqlcipher_extra_init \
	-DSQLITE_EXTRA_SHUTDOWN=sqlcipher_extra_shutdown \
	-DSQLCIPHER_CRYPTO_LEANCRYPTO \
	-DSQLITE_THREADSAFE=1 \
	-DSQLITE_TEMP_STORE=2 \
	-DSQLITE_ENABLE_FTS5 \
	-DBUILD_sqlite \
	-I"$GEN_DIR" \
	-I"$GEN_DIR/build" \
	-I"$TOP/src" \
	-I"$LC_DIR/aead/api" -I"$LC_DIR/hash/api" -I"$LC_DIR/kdf/api" \
	-I"$LC_DIR/internal/api" -I"$LC_DIR/sym/api" -I"$LC_DIR/hmac/api" \
	-I"$LC_DIR/drng/api" \
	-I"$LC_BUILD_DIR/internal/api" -I"$LC_BUILD_DIR/hash/api" \
	"$GEN_DIR/sqlite3.c" \
	"$TOP/src/crypto_leancrypto.c" \
	"$TOP/src/crypto_leancrypto_rng_wasm.c" \
	"$TOP/wasm/leancrypto_wasm_api.c" \
	-Wl,--whole-archive "$LC_LIB" -Wl,--no-whole-archive \
	-s WASM=1 \
	-s MODULARIZE=1 \
	-s EXPORT_NAME="Sqlite3Wasm" \
	-s EXPORT_ALL=1 \
	-Wl,--export-all \
	-Wl,--no-gc-sections \
	-s ALLOW_MEMORY_GROWTH=1 \
	-s EXPORTED_RUNTIME_METHODS='["ccall","cwrap","getValue","setValue","UTF8ToString","stringToUTF8","lengthBytesUTF8"]' \
	-o "$OUT_DIR/sqlcipher.js"

echo "Done: $OUT_DIR/sqlcipher.js  $OUT_DIR/sqlcipher.wasm"
